version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  postgres:
    image: postgres:latest
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build:
      context: ./api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./api:/app
    environment: 
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432